OpenOrchestra\ModelInterface\Model\NodeInterface:
    constraints:
        - OpenOrchestra\Backoffice\Validator\Constraints\BlockNodePattern: ~
        - OpenOrchestra\Backoffice\Validator\Constraints\RestoreNode: { groups: [restore] }
        - OpenOrchestra\Backoffice\Validator\Constraints\CheckAreaPresence: ~
        - OpenOrchestra\Backoffice\Validator\Constraints\UniqueNodeOrder: ~
