parameters:
    open_orchestra_workflow_function_admin.manager.workflow_right.class: OpenOrchestra\WorkflowFunctionAdminBundle\Manager\WorkflowRightManager

services:
    open_orchestra_workflow_function_admin.manager.workflow_right:
        class: %open_orchestra_workflow_function_admin.manager.workflow_right.class%
        arguments:
            - @open_orchestra_model.repository.content_type
            - @open_orchestra_workflow_function.repository.workflow_right
            - @open_orchestra_workflow_function.manager.authorization_workflow_right
            - %open_orchestra_workflow_function.document.workflow_right.class%
