parameters:
    php_orchestra_log.subscriber.node.class: PHPOrchestra\LogBundle\EventSubscriber\LogNodeSubscriber
    php_orchestra_log.subscriber.content.class: PHPOrchestra\LogBundle\EventSubscriber\LogContentSubscriber
    php_orchestra_log.subscriber.content_type.class: PHPOrchestra\LogBundle\EventSubscriber\LogContentTypeSubscriber
    php_orchestra_log.subscriber.keyword.class: PHPOrchestra\LogBundle\EventSubscriber\LogKeywordSubscriber
    php_orchestra_log.subscriber.media.class: PHPOrchestra\LogBundle\EventSubscriber\LogMediaSubscriber
    php_orchestra_log.subscriber.role.class: PHPOrchestra\LogBundle\EventSubscriber\LogRoleSubscriber
    php_orchestra_log.subscriber.site.class: PHPOrchestra\LogBundle\EventSubscriber\LogSiteSubscriber
    php_orchestra_log.subscriber.status.class: PHPOrchestra\LogBundle\EventSubscriber\LogStatusSubscriber
    php_orchestra_log.subscriber.template.class: PHPOrchestra\LogBundle\EventSubscriber\LogTemplateSubscriber
    php_orchestra_log.subscriber.theme.class: PHPOrchestra\LogBundle\EventSubscriber\LogThemeSubscriber

services:
    php_orchestra_log.subscriber.node:
        class: %php_orchestra_log.subscriber.node.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.content:
        class: %php_orchestra_log.subscriber.content.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.content_type:
        class: %php_orchestra_log.subscriber.content_type.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.keyword:
        class: %php_orchestra_log.subscriber.keyword.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.media:
        class: %php_orchestra_log.subscriber.media.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.role:
        class: %php_orchestra_log.subscriber.role.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.site:
        class: %php_orchestra_log.subscriber.site.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.status:
        class: %php_orchestra_log.subscriber.status.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.template:
        class: %php_orchestra_log.subscriber.template.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
    php_orchestra_log.subscriber.theme:
        class: %php_orchestra_log.subscriber.theme.class%
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phporchestra }
