parameters:
    open_orchestra_backoffice.authorize_edition.manager.class: OpenOrchestra\BackofficeBundle\StrategyManager\AuthorizeEditionManager
    open_orchestra_backoffice.authorize_edition.statusable.class: OpenOrchestra\Backoffice\AuthorizeEdition\StatusableStrategy
    open_orchestra_backoffice.authorize_edition.node_version.class: OpenOrchestra\Backoffice\AuthorizeEdition\NodeVersionStrategy

services:
    open_orchestra_backoffice.authorize_edition.manager:
        class: %open_orchestra_backoffice.authorize_edition.manager.class%

    open_orchestra_backoffice.authorize_edition.statusable:
        class: %open_orchestra_backoffice.authorize_edition.statusable.class%
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }
    open_orchestra_backoffice.authorize_edition.node_version:
        class: %open_orchestra_backoffice.authorize_edition.node_version.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }