parameters:
    open_orchestra_backoffice.collector.backoffice_role.class: OpenOrchestra\Backoffice\Collector\BackofficeRoleCollector

services:
    open_orchestra_backoffice.collector.backoffice_role:
        class: %open_orchestra_backoffice.collector.backoffice_role.class%
        arguments:
            - @open_orchestra_model.repository.role
            - @translator
            - @open_orchestra_backoffice.manager.translation_choice
            - %open_orchestra_backoffice.collector.backoffice_role.workflow_role_in_group%
