parameters:
    php_orchestra_backoffice.generate_form_manager.class: PHPOrchestra\BackofficeBundle\StrategyManager\GenerateFormManager
    php_orchestra_backoffice.sample.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SampleStrategy
    php_orchestra_backoffice.contact.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\ContactStrategy
    php_orchestra_backoffice.carrousel.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\CarrouselStrategy
    php_orchestra_backoffice.footer.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\FooterStrategy
    php_orchestra_backoffice.header.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\HeaderStrategy
    php_orchestra_backoffice.menu.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\MenuStrategy
    php_orchestra_backoffice.news.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\NewsStrategy
    php_orchestra_backoffice.tinymcewysiwyg.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\TinyMCEWysiwygStrategy
    php_orchestra_backoffice.search.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SearchStrategy
    php_orchestra_backoffice.search_result.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SearchResultStrategy
    php_orchestra_backoffice.configurable_content.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\ConfigurableContentStrategy
    php_orchestra_backoffice.sub_menu.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SubMenuStrategy
    php_orchestra_backoffice.content_list.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\ContentListStrategy
    php_orchestra_backoffice.media_list_by_keyword.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\MediaListByKeywordStrategy
    php_orchestra_backoffice.content.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\ContentStrategy
    php_orchestra_backoffice.language_list.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\LanguageListStrategy

services:
    php_orchestra_backoffice.generate_form_manager:
        class: %php_orchestra_backoffice.generate_form_manager.class%

    php_orchestra_backoffice.sample.generate_form:
        class: %php_orchestra_backoffice.sample.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.contact.generate_form:
        class: %php_orchestra_backoffice.contact.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.carrousel.generate_form:
        class: %php_orchestra_backoffice.carrousel.generate_form.class%
        arguments:
            - @translator
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.footer.generate_form:
        class: %php_orchestra_backoffice.footer.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.header.generate_form:
        class: %php_orchestra_backoffice.header.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.menu.generate_form:
        class: %php_orchestra_backoffice.menu.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.news.generate_form:
        class: %php_orchestra_backoffice.news.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.tinymcewysiwyg.generate_form:
        class: %php_orchestra_backoffice.tinymcewysiwyg.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.search.generate_form:
        class: %php_orchestra_backoffice.search.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.search_result.generate_form:
        class: %php_orchestra_backoffice.search_result.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.configurable_content.generate_form:
        class: %php_orchestra_backoffice.configurable_content.generate_form.class%
        arguments: 
            - @php_orchestra_model.repository.content_type
            - @php_orchestra_model.repository.content
            - @router
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.sub_menu.generate_form:
        class: %php_orchestra_backoffice.sub_menu.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.content_lis.generate_form:
        class: %php_orchestra_backoffice.content_list.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.media_list_by_keyword.generate_form:
        class: %php_orchestra_backoffice.media_list_by_keyword.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.content.generate_form:
        class: %php_orchestra_backoffice.content.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.language_list.generate_form:
        class: %php_orchestra_backoffice.language_list.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.generate_form.youtube:
        class: PHPOrchestra\Backoffice\GenerateForm\Strategies\YoutubeStrategy
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.generate_form.dailymotion:
        class: PHPOrchestra\Backoffice\GenerateForm\Strategies\DailymotionStrategy
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.generate_form.vimeo:
        class: PHPOrchestra\Backoffice\GenerateForm\Strategies\VimeoStrategy
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.generate_form.gmap:
        class: PHPOrchestra\Backoffice\GenerateForm\Strategies\GmapStrategy
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.generate_form.add_this:
        class: PHPOrchestra\Backoffice\GenerateForm\Strategies\AddThisStrategy
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
