parameters:
    php_orchestra_backoffice.generate_form_manager.class: PHPOrchestra\BackofficeBundle\StrategyManager\GenerateFormManager
    php_orchestra_backoffice.sample.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SampleStrategy
    php_orchestra_backoffice.contact.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\ContactStrategy
    php_orchestra_backoffice.carrousel.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\CarrouselStrategy
    php_orchestra_backoffice.footer.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\FooterStrategy
    php_orchestra_backoffice.header.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\HeaderStrategy
    php_orchestra_backoffice.menu.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\MenuStrategy
    php_orchestra_backoffice.news.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\NewsStrategy
    php_orchestra_backoffice.tinymcewysiwyg.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\TinyMCEWysiwygStrategy
    php_orchestra_backoffice.search.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SearchStrategy
    php_orchestra_backoffice.search_result.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\SearchResultStrategy
    php_orchestra_backoffice.configurable_content.generate_form.class: PHPOrchestra\Backoffice\GenerateForm\Strategies\ConfigurableContentStrategy

services:
    php_orchestra_backoffice.generate_form_manager:
        class: %php_orchestra_backoffice.generate_form_manager.class%

    php_orchestra_backoffice.sample.generate_form:
        class: %php_orchestra_backoffice.sample.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.contact.generate_form:
        class: %php_orchestra_backoffice.contact.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.carrousel.generate_form:
        class: %php_orchestra_backoffice.carrousel.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.footer.generate_form:
        class: %php_orchestra_backoffice.footer.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.header.generate_form:
        class: %php_orchestra_backoffice.header.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.menu.generate_form:
        class: %php_orchestra_backoffice.menu.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.news.generate_form:
        class: %php_orchestra_backoffice.news.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.tinymcewysiwyg.generate_form:
        class: %php_orchestra_backoffice.tinymcewysiwyg.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.search.generate_form:
        class: %php_orchestra_backoffice.search.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.search_result.generate_form:
        class: %php_orchestra_backoffice.search_result.generate_form.class%
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
    php_orchestra_backoffice.configurable_content.generate_form:
        class: %php_orchestra_backoffice.configurable_content.generate_form.class%
        arguments: 
            - @php_orchestra_model.repository.content_type
            - @php_orchestra_model.repository.content
            - @router
            - @translator
        tags:
            - { name: php_orchestra_backoffice.generate_form.strategy }
            