parameters:
    open_orchestra_backoffice.display_icon_manager.class: OpenOrchestra\Backoffice\DisplayIcon\DisplayManager
    open_orchestra_backoffice.display_icon.contact.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\ContactStrategy
    open_orchestra_backoffice.display_icon.footer.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\FooterStrategy
    open_orchestra_backoffice.display_icon.menu.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\MenuStrategy
    open_orchestra_backoffice.display_icon.sample.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\SampleStrategy
    open_orchestra_backoffice.display_icon.tiny_mce_wysiwyg.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\TinyMCEWysiwygStrategy
    open_orchestra_backoffice.display_icon.configurable_content.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\ConfigurableContentStrategy
    open_orchestra_backoffice.display_icon.search.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\SearchStrategy
    open_orchestra_backoffice.display_icon.search_result.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\SearchResultStrategy
    open_orchestra_backoffice.display_icon.login.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\LoginStrategy
    open_orchestra_backoffice.display_icon.sub_menu.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\SubMenuStrategy
    open_orchestra_backoffice.display_icon.content_list.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\ContentListStrategy
    open_orchestra_backoffice.display_icon.content.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\ContentStrategy
    open_orchestra_backoffice.display_icon.language_list.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\LanguageListStrategy
    open_orchestra_backoffice.display_icon.audience_analysis.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\AudienceAnalysisStrategy
    open_orchestra_backoffice.display_icon.gmap.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\GmapStrategy
    open_orchestra_backoffice.display_icon.add_this.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\AddThisStrategy
    open_orchestra_backoffice.display_icon.video.class: OpenOrchestra\Backoffice\DisplayIcon\Strategies\VideoStrategy

services:
    open_orchestra_backoffice.display_icon_manager:
        class: %open_orchestra_backoffice.display_icon_manager.class%
        calls:
            - [ setContainer,[ @service_container ] ]
    open_orchestra_backoffice.display_icon.contact:
        class: %open_orchestra_backoffice.display_icon.contact.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.footer:
        class: %open_orchestra_backoffice.display_icon.footer.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.menu:
        class: %open_orchestra_backoffice.display_icon.menu.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.search_result:
        class: %open_orchestra_backoffice.display_icon.search_result.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.search:
        class: %open_orchestra_backoffice.display_icon.search.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.login:
        class: %open_orchestra_backoffice.display_icon.login.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.sub_menu:
        class: %open_orchestra_backoffice.display_icon.sub_menu.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.content_list:
        class: %open_orchestra_backoffice.display_icon.content_list.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.content:
        class: %open_orchestra_backoffice.display_icon.content.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.language_list:
        class: %open_orchestra_backoffice.display_icon.language_list.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.tiny_mce_wysiwyg:
        class: %open_orchestra_backoffice.display_icon.tiny_mce_wysiwyg.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.display_icon.configurable_content:
        class: %open_orchestra_backoffice.display_icon.configurable_content.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.icon.gmap:
        class: %open_orchestra_backoffice.display_icon.gmap.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.icon.add_this:
        class: %open_orchestra_backoffice.display_icon.add_this.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.icon.audience_analysis:
        class: %open_orchestra_backoffice.display_icon.audience_analysis.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
    open_orchestra_backoffice.icon.video:
        class: %open_orchestra_backoffice.display_icon.video.class%
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }
