parameters:
    php_orchestra_backoffice.display_icon_manager.class: PHPOrchestra\BackofficeBundle\DisplayIcons\DisplayIconManager

    php_orchestra_backoffice.display_icon.carrousel.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\CarrouselIconStrategy
    php_orchestra_backoffice.display_icon.contact.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\ContactIconStrategy
    php_orchestra_backoffice.display_icon.header.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\HeaderIconStrategy
    php_orchestra_backoffice.display_icon.footer.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\FooterIconStrategy
    php_orchestra_backoffice.display_icon.menu.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\MenuIconStrategy
    php_orchestra_backoffice.display_icon.sample.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\SampleIconStrategy
    php_orchestra_backoffice.display_icon.tiny_mce_wysiwyg.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\TinyMCEWysiwygIconStrategy
    php_orchestra_backoffice.display_icon.configurable_content.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\ConfigurableContentIconStrategy
    php_orchestra_backoffice.display_icon.search.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\SearchIconStrategy
    php_orchestra_backoffice.display_icon.search_result.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\SearchResultIconStrategy
    php_orchestra_backoffice.display_icon.login.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\LoginIconStrategy
    php_orchestra_backoffice.display_icon.sub_menu.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\SubMenuIconStrategy
    php_orchestra_backoffice.display_icon.content_list_by_keyword.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\ContentListByKeywordIconStrategy
    php_orchestra_backoffice.display_icon.content_list_by_type.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\ContentListByTypeIconStrategy
    php_orchestra_backoffice.display_icon.content.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\ContentIconStrategy
    php_orchestra_backoffice.display_icon.language_list.class: PHPOrchestra\BackofficeBundle\DisplayIcons\Strategies\LanguageListIconStrategy

services:
    php_orchestra_backoffice.display_icon_manager:
        class: %php_orchestra_backoffice.display_icon_manager.class%
        arguments: [@service_container]
    php_orchestra_backoffice.display_icon.contact:
        class: %php_orchestra_backoffice.display_icon.contact.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.footer:
        class: %php_orchestra_backoffice.display_icon.footer.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.menu:
        class: %php_orchestra_backoffice.display_icon.menu.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.search_result:
        class: %php_orchestra_backoffice.display_icon.search_result.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.search:
        class: %php_orchestra_backoffice.display_icon.search.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.login:
        class: %php_orchestra_backoffice.display_icon.login.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.sub_menu:
        class: %php_orchestra_backoffice.display_icon.sub_menu.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.content_list_by_keyword:
        class: %php_orchestra_backoffice.display_icon.content_list_by_keyword.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.content_list_by_type:
        class: %php_orchestra_backoffice.display_icon.content_list_by_type.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.content:
        class: %php_orchestra_backoffice.display_icon.content.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.language_list:
        class: %php_orchestra_backoffice.display_icon.language_list.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.carrousel:
        class: %php_orchestra_backoffice.display_icon.carrousel.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.tiny_mce_wysiwyg:
        class: %php_orchestra_backoffice.display_icon.tiny_mce_wysiwyg.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.header:
        class: %php_orchestra_backoffice.display_icon.header.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.configurable_content:
        class: %php_orchestra_backoffice.display_icon.configurable_content.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
