parameters:
    php_orchestra_backoffice.display_icon_manager.class: PHPOrchestra\BackofficeBundle\DisplayIcon\DisplayManager
    php_orchestra_backoffice.display_icon.carrousel.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\CarrouselStrategy
    php_orchestra_backoffice.display_icon.contact.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\ContactStrategy
    php_orchestra_backoffice.display_icon.header.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\HeaderStrategy
    php_orchestra_backoffice.display_icon.footer.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\FooterStrategy
    php_orchestra_backoffice.display_icon.menu.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\MenuStrategy
    php_orchestra_backoffice.display_icon.sample.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\SampleStrategy
    php_orchestra_backoffice.display_icon.tiny_mce_wysiwyg.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\TinyMCEWysiwygStrategy
    php_orchestra_backoffice.display_icon.configurable_content.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\ConfigurableContentStrategy
    php_orchestra_backoffice.display_icon.search.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\SearchStrategy
    php_orchestra_backoffice.display_icon.search_result.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\SearchResultStrategy
    php_orchestra_backoffice.display_icon.login.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\LoginStrategy
    php_orchestra_backoffice.display_icon.sub_menu.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\SubMenuStrategy
    php_orchestra_backoffice.display_icon.content_list.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\ContentListStrategy
    php_orchestra_backoffice.display_icon.media_list.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\MediaListStrategy
    php_orchestra_backoffice.display_icon.content.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\ContentStrategy
    php_orchestra_backoffice.display_icon.language_list.class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\LanguageListStrategy

services:
    php_orchestra_backoffice.display_icon_manager:
        class: %php_orchestra_backoffice.display_icon_manager.class%
        arguments: [@service_container]
    php_orchestra_backoffice.display_icon.contact:
        class: %php_orchestra_backoffice.display_icon.contact.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.footer:
        class: %php_orchestra_backoffice.display_icon.footer.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.menu:
        class: %php_orchestra_backoffice.display_icon.menu.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.search_result:
        class: %php_orchestra_backoffice.display_icon.search_result.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.search:
        class: %php_orchestra_backoffice.display_icon.search.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.login:
        class: %php_orchestra_backoffice.display_icon.login.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.sub_menu:
        class: %php_orchestra_backoffice.display_icon.sub_menu.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.content_list:
        class: %php_orchestra_backoffice.display_icon.content_list.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.media_list:
        class: %php_orchestra_backoffice.display_icon.media_list.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.content:
        class: %php_orchestra_backoffice.display_icon.content.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.language_list:
        class: %php_orchestra_backoffice.display_icon.language_list.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.carrousel:
        class: %php_orchestra_backoffice.display_icon.carrousel.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.tiny_mce_wysiwyg:
        class: %php_orchestra_backoffice.display_icon.tiny_mce_wysiwyg.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.header:
        class: %php_orchestra_backoffice.display_icon.header.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.display_icon.configurable_content:
        class: %php_orchestra_backoffice.display_icon.configurable_content.class%
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.icon.youtube:
        class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\YoutubeStrategy
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
    php_orchestra_backoffice.icon.dailymotion:
        class: PHPOrchestra\BackofficeBundle\DisplayIcon\Strategies\DailymotionStrategy
        tags:
            - { name: php_orchestra_backoffice.display_icon.strategy }
