parameters:
    open_orchestra_backoffice.left_panel_manager.class: OpenOrchestra\BackofficeBundle\StrategyManager\LeftPanelManager
    open_orchestra_backoffice.left_panel.node.class: OpenOrchestra\Backoffice\LeftPanel\Strategies\TreeNodesPanelStrategy
    open_orchestra_backoffice.left_panel.folder.class: OpenOrchestra\Backoffice\LeftPanel\Strategies\TreeFolderPanelStrategy
    open_orchestra_backoffice.left_panel.template.class: OpenOrchestra\Backoffice\LeftPanel\Strategies\TreeTemplatePanelStrategy
    open_orchestra_backoffice.left_panel.content_type.class: OpenOrchestra\Backoffice\LeftPanel\Strategies\ContentTypeForContentPanelStrategy
    open_orchestra_backoffice.left_panel.general_node.class: OpenOrchestra\Backoffice\LeftPanel\Strategies\GeneralNodesPanelStrategy
    open_orchestra_backoffice.left_panel.administration.class: OpenOrchestra\Backoffice\LeftPanel\Strategies\AdministrationPanelStrategy

services:
    open_orchestra_backoffice.left_panel_manager:
        class: %open_orchestra_backoffice.left_panel_manager.class%
        arguments:
            - @service_container
    open_orchestra_backoffice.left_panel.node:
        class: %open_orchestra_backoffice.left_panel.node.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.folder:
        class: %open_orchestra_backoffice.left_panel.folder.class%
        arguments:
            - @open_orchestra_media.repository.media_folder
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.template:
        class: %open_orchestra_backoffice.left_panel.template.class%
        arguments:
            - @open_orchestra_model.repository.template
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.content_type:
        class: %open_orchestra_backoffice.left_panel.content_type.class%
        arguments:
            - @open_orchestra_model.repository.content_type
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.general_node:
        class: %open_orchestra_backoffice.left_panel.general_node.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.content_types:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - content_types
            - ROLE_ACCESS_CONTENT_TYPE
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.keywords:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - keywords
            - ROLE_ACCESS_KEYWORD
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.role:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - role
            - ROLE_ACCESS_ROLE
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.group:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - group
            - ROLE_ACCESS_GROUP
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.redirection:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - redirection
            - ROLE_ACCESS_REDIRECTION
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.status:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - status
            - ROLE_ACCESS_STATUS
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.themes:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - themes
            - ROLE_ACCESS_THEME
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.user:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - user
            - ROLE_ACCESS_USER
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.websites:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - websites
            - ROLE_ACCESS_SITE
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }

    open_orchestra_backoffice.left_panel.deleted:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - deleted
            - ROLE_ACCESS_DELETED
            - 0
            - editorial
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
    open_orchestra_backoffice.left_panel.log:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - logs
            - ROLE_ACCESS_LOG
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
