parameters:
    php_orchestra_backoffice.manager.context.class: PHPOrchestra\Backoffice\Context\TestContextManager

services:
    php_orchestra_backoffice.context_manager:
        class: "%php_orchestra_backoffice.manager.context.class%"
        arguments: [@php_orchestra_model.repository.site, "%kernel.default_locale%"]