parameters:

#--[CHOICES PARAMETERS]---------#

    php_orchestra.orchestra_choice.status:
        STATUS_DRAFT: draft
        STATUS_PENDING: pending
        STATUS_PUBLISHED: published
    php_orchestra.orchestra_choice.language:
        fr: Fran√ßais
        en: English
    php_orchestra.orchestra_choice.direction:
        h: Horizontal
        v: Vertical

#--[CUSTOM FIELDS]--------------#
    
    php_orchestra_cms.custom_types:
        
        orchestra_text:
            type: text
            options:
                max_length:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.max_length
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
        orchestra_textarea:
            type: textarea
            options:
                max_length:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.max_length
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
        orchestra_integer:
            type: integer
            options:
                rounding_mode:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.rounding_mode
                    default_value: 0
                    required: true
                grouping:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.format
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
        orchestra_email:
            type: email
            options:
                max_length:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.max_length
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        