parameters:
    php_orchestra_cms.type.content.class : PHPOrchestra\CMSBundle\Form\Type\ContentType
    php_orchestra_cms.type.content_type.class : PHPOrchestra\CMSBundle\Form\Type\ContentTypeType

services:
    # Content Form Builder
    php_orchestra_cms.type.content:
        class: %php_orchestra_cms.type.content.class%
        arguments: [@php_orchestra_cms.context_manager]
        tags: [{name: form.type, alias: content}]

    # ContentType Form Builder
    php_orchestra_cms.type.content_type:
        class: %php_orchestra_cms.type.content_type.class%
        arguments: [@jms_serializer, "%php_orchestra_cms.custom_types%"]
        tags: [{name: form.type, alias: content_type}]

    # Site Form Builder
    php_orchestra_cms.type.site:
        class: PHPOrchestra\CMSBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }
