php_orchestra_cms:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /

php_orchestra_cms_bo:
    pattern: /admin
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/BackOffice:home }

php_orchestra_cms_bo_edito:
    pattern: /edito
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/BackOffice:edito }

php_orchestra_cms_bo_site:
    resource: "@PHPOrchestraCMSBundle/Controller/BackOfficeView/SiteController.php"
    type: annotation

php_orchestra_cms_bo_contentType:
    resource: "@PHPOrchestraCMSBundle/Controller/BackOfficeView/ContentTypeController.php"
    type: annotation

php_orchestra_cms_bo_contentType_ajaxmenu:
    pattern: /ajax/contenttype/menu/{language}/{siteId}
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/ContentType:ajaxMenu, language: 'fr', siteId: '' }

php_orchestra_cms_bo_content:
    resource: "@PHPOrchestraCMSBundle/Controller/BackOfficeView/ContentController.php"
    type: annotation

php_orchestra_cms_bo_jscontextmenudispatcher:
    pattern: /admin/js-menu-dispatcher/{cmd}
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/BackOffice:jsContextMenuDispatch, cmd: '' }

php_orchestra_cms_templateform:
    pattern: /admin/template/form/{templateId}
    defaults: { _controller: PHPOrchestraCMSBundle:Template:form, templateId: 0 }

php_orchestra_cms_templateajaxrequest:
    pattern: /admin/template/ajaxRequest/{templateId}
    defaults: { _controller: PHPOrchestraCMSBundle:Template:ajaxRequest}

php_orchestra_setLanguage:
    pattern: /ajax/context/setLanguage/{language}
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/Context:SetLanguage, language:en }

php_orchestra_setSite:
    pattern: /ajax/context/setSite/{siteId}/{siteDomain}
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/Context:SetSite}
