parameters:
    php_orchestra_cms.manager.document.class : 'PHPOrchestra\CMSBundle\Document\DocumentManager'
    php_orchestra_cms.manager.context.class : 'PHPOrchestra\CMSBundle\Context\ContextManager'
    php_orchestra_cms.type.multilingual_text.class : 'PHPOrchestra\CMSBundle\Form\Type\MultilingualTextType'
    php_orchestra_cms.type.content_attributes.class : 'PHPOrchestra\CMSBundle\Form\Type\ContentAttributesType'
    php_orchestra_cms.type.content_type_fields.class : 'PHPOrchestra\CMSBundle\Form\Type\ContentTypeFieldsType'
    php_orchestra_cms.type.custom_field.class : 'PHPOrchestra\CMSBundle\Form\Type\CustomFieldType'

services:

#--[STANDARD SERVICES]----------#
    # DocumentManager service
    php_orchestra_cms.document_manager:
        class: "%php_orchestra_cms.manager.document.class%"
        arguments: [@mandango]

    # Context service
    php_orchestra_cms.context_manager:
        class: "%php_orchestra_cms.manager.context.class%"
        arguments: [@session, @php_orchestra_model.repository.site, "%kernel.default_locale%"]

#--[FORM FIELDS]----------------#

    # Multilingual text field
    php_orchestra_cms.type.multilingual_text:
        class: "%php_orchestra_cms.type.multilingual_text.class%"
        arguments: ["%php_orchestra_base.languages_availables%"]
        tags: [{name: form.type, alias: multilingualText}]

    # Orchestra content type attributes
    php_orchestra_cms.type.content_attributes:
        class: "%php_orchestra_cms.type.content_attributes.class%"
        arguments: [@php_orchestra_cms.document_manager]
        tags: [{name: form.type, alias: contentAttributes}]

    # Content type fields 
    php_orchestra_cms.type.content_type_fields:
        class: "%php_orchestra_cms.type.content_type_fields.class%"
        tags: [{name: form.type, alias: content_type_fields}]

    # Custom field
    php_orchestra_cms.type.custom_field:
        class: "%php_orchestra_cms.type.custom_field.class%"
        arguments: ["%php_orchestra_cms.custom_types%"]
        tags: [{name: form.type, alias: orchestra_customField}]

    # Status form field type
    php_orchestra_cms.type.status:
        class: PHPOrchestra\CMSBundle\Form\Type\StatusType
        arguments: 
            - "%php_orchestra.orchestra_choice.status%"
        tags:
            - { name: form.type, alias: orchestra_status }

    # Language form field type
    php_orchestra_cms.type.language:
        class: PHPOrchestra\CMSBundle\Form\Type\LanguageType
        arguments: 
            - "%php_orchestra.orchestra_choice.language%"
        tags:
            - { name: form.type, alias: orchestra_language }

    # Direction form field type
    php_orchestra_cms.type.direction:
        class: PHPOrchestra\CMSBundle\Form\Type\DirectionType
        arguments: 
            - "%php_orchestra.orchestra_choice.direction%"
        tags:
            - { name: form.type, alias: orchestra_direction }
