services:

#--[STANDARD SERVICES]----------#

    # Cache service
    php_orchestra_cms.cache_manager:
        class: "%php_orchestra_cms.manager.cache.class%"
        arguments: [@snc_redis.default]

    # DocumentManager service
    php_orchestra_cms.document_manager:
        class: "%php_orchestra_cms.manager.document.class%"
        arguments: [@mandango]

    # Context service
    php_orchestra_cms.context_manager:
        class: "%php_orchestra_cms.manager.context.class%"
        arguments: [@session, @php_orchestra_cms.document_manager, "%kernel.default_locale%"]

    # Locale listener
    php_orchestra_cms.locale_listener:
        class: "%php_orchestra_cms.listener.locale.class%"
        arguments: ["%kernel.default_locale%"]
        tags: [{name: kernel.event_subscriber}]

#--[CONTROLLER SERVICES]----------#

    # Render Block Controller
    phporchestra_cms.blockcontroller:
        class: PHPOrchestra\CMSBundle\Controller\BlockController

#--[FORM FIELDS]----------------#

    # Multilingual text field
    php_orchestra_cms.type.multilingual_text:
        class: "%php_orchestra_cms.type.multilingual_text.class%"
        arguments: ["%php_orchestra_cms.languages.availables%"]
        tags: [{name: form.type, alias: multilingualText}]

    # Orchestra content type attributes
    php_orchestra_cms.type.content_attributes:
        class: "%php_orchestra_cms.type.content_attributes.class%"
        arguments: [@php_orchestra_cms.document_manager]
        tags: [{name: form.type, alias: contentAttributes}]

    # Content type fields 
    php_orchestra_cms.type.content_type_fields:
        class: "%php_orchestra_cms.type.content_type_fields.class%"
        tags: [{name: form.type, alias: content_type_fields}]

    # Custom field
    php_orchestra_cms.type.custom_field:
        class: "%php_orchestra_cms.type.custom_field.class%"
        arguments: [@service_container]
        tags: [{name: form.type, alias: orchestra_customField}]

    # Areas form field type
    php_orchestra_cms.type.areas:
        class: PHPOrchestra\CMSBundle\Form\Type\AreasType
        tags:
            - { name: form.type, alias: orchestra_areas }

    # Blocks form field type
    php_orchestra_cms.type.blocks:
        class: PHPOrchestra\CMSBundle\Form\Type\BlocksType
        arguments: [@php_orchestra_cms.document_manager]
        tags:
            - { name: form.type, alias: orchestra_blocks }

    # Templates select form field type
    php_orchestra_cms.type.template_choice:
        class: PHPOrchestra\CMSBundle\Form\Type\TemplateChoiceType
        arguments: [@php_orchestra_cms.document_manager]
        tags:
            - { name: form.type, alias: orchestra_template_choice }

    # Block select after node form field type
    php_orchestra_cms.type.block:
        class: PHPOrchestra\CMSBundle\Form\Type\BlockType
        arguments: [@php_orchestra_cms.document_manager]
        tags:
            - { name: form.type, alias: blocks }

    # Block select form field type
    php_orchestra_cms.type.block_choice:
        class: PHPOrchestra\CMSBundle\Form\Type\BlockChoiceType
        arguments: [@php_orchestra_cms.document_manager, "%php_orchestra.blocks%", 0, 0]
        tags:
            - { name: form.type, alias: orchestra_block_choice }

    # Nodes select form field type
    php_orchestra_cms.type.node_choice:
        class: PHPOrchestra\CMSBundle\Form\Type\NodeChoiceType
        arguments: [@php_orchestra_cms.document_manager]
        tags:
            - { name: form.type, alias: orchestra_node_choice }

    # Status form field type
    php_orchestra_cms.type.status:
        class: PHPOrchestra\CMSBundle\Form\Type\StatusType
        arguments: 
            - "%php_orchestra.orchestra_choice.status%"
        tags:
            - { name: form.type, alias: orchestra_status }

    # Language form field type
    php_orchestra_cms.type.language:
        class: PHPOrchestra\CMSBundle\Form\Type\LanguageType
        arguments: 
            - "%php_orchestra.orchestra_choice.language%"
        tags:
            - { name: form.type, alias: orchestra_language }

    # Direction form field type
    php_orchestra_cms.type.direction:
        class: PHPOrchestra\CMSBundle\Form\Type\DirectionType
        arguments: 
            - "%php_orchestra.orchestra_choice.direction%"
        tags:
            - { name: form.type, alias: orchestra_direction }

#--[FORM]-----------------------#

    # Content Form Builder
    php_orchestra_cms.type.content:
        class: "%php_orchestra_cms.type.content.class%"
        arguments: [@php_orchestra_cms.context_manager]
        tags: [{name: form.type, alias: content}]

    # ContentType Form Builder
    php_orchestra_cms.type.content_type:
        class: "%php_orchestra_cms.type.content_type.class%"
        arguments: [@jms_serializer, "%php_orchestra_cms.custom_types%"]
        tags: [{name: form.type, alias: content_type}]

    # Site Form Builder
    php_orchestra_cms.type.site:
        class: PHPOrchestra\CMSBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }

    # Template form type
    php_orchestra_cms.type.template:
        class: PHPOrchestra\CMSBundle\Form\Type\TemplateType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: template }

    # Node form type
    php_orchestra_cms.type.node:
        class: PHPOrchestra\CMSBundle\Form\Type\NodeType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: node }

#--[TWIG]-----------------------#

    php_orchestra_cms.twig.lexicon_translator:
        class: PHPOrchestra\CMSBundle\Twig\LexiconTranslatorExtension
        tags:
            - { name: twig.extension }
    php_orchestra_cms.twig.add_html:
        class: PHPOrchestra\CMSBundle\Twig\AddHtmlExtension
        tags:
            - { name: twig.extension }
    php_orchestra_cms.twig.php_function:
        class: PHPOrchestra\CMSBundle\Twig\AddPhpFunctionExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }