parameters:
    php_orchestra_cms.twig.tree.extension.class: PHPOrchestra\CMSBundle\Twig\TreeHelperExtension
    php_orchestra_cms.twig.display_field.extension.class: PHPOrchestra\CMSBundle\Twig\DisplayFieldExtension

services:
    php_orchestra_cms.twig.tree.extension:
        class: %php_orchestra_cms.twig.tree.extension.class%
        arguments: [@php_orchestra_cms.manager.tree]
        tags:
            - { name: twig.extension }
    php_orchestra_cms.twig.display_field.extension:
        class: %php_orchestra_cms.twig.display_field.extension.class%
        arguments: [@php_orchestra_cms.display_field_manager]
        tags:
            - { name: twig.extension }