parameters:
    open_orchestra_media_admin.slideshow.generate_form.class: OpenOrchestra\MediaAdminBundle\GenerateForm\Strategies\SlideshowStrategy
    open_orchestra_media_admin.gallery.generate_form.class: OpenOrchestra\MediaAdminBundle\GenerateForm\Strategies\GalleryStrategy
    open_orchestra_media_admin.media_list_by_keyword.generate_form.class: OpenOrchestra\MediaAdminBundle\GenerateForm\Strategies\MediaListByKeywordStrategy
    open_orchestra_media_admin.display_media.generate_form.class: OpenOrchestra\MediaAdminBundle\GenerateForm\Strategies\DisplayMediaStrategy

services:
    open_orchestra_media_admin.slideshow.generate_form:
        class: %open_orchestra_media_admin.slideshow.generate_form.class%
        arguments:
            - @translator
        tags:
            - { name: open_orchestra_backoffice.generate_form.strategy }
    open_orchestra_media_admin.gallery.generate_form:
        class: %open_orchestra_media_admin.gallery.generate_form.class%
        arguments:
            - @translator
            - %open_orchestra_media.thumbnail.configuration%
        tags:
            - { name: open_orchestra_backoffice.generate_form.strategy }
    open_orchestra_media_admin.media_list_by_keyword.generate_form:
        class: %open_orchestra_media_admin.media_list_by_keyword.generate_form.class%
        tags:
            - { name: open_orchestra_backoffice.generate_form.strategy }
    open_orchestra_media_admin.display_media.generate_form:
        class: %open_orchestra_media_admin.display_media.generate_form.class%
        arguments:
            - @translator
            - %open_orchestra_media.thumbnail.configuration%
        tags:
            - { name: open_orchestra_backoffice.generate_form.strategy }
