parameters:
    open_orchestra_mediaadmin.left_panel.folder.class: OpenOrchestra\MediaAdminBundle\LeftPanel\Strategies\TreeFolderPanelStrategy

services:
    open_orchestra_mediaadmin.left_panel.folder:
        class: %open_orchestra_mediaadmin.left_panel.folder.class%
        arguments:
            - @open_orchestra_media.repository.media_folder
        tags:
            - { name: open_orchestra_mediaadmin.left_panel.strategy }