parameters:
    php_orchestra_api.transformer_manager.class: PHPOrchestra\ApiBundle\Transformer\TransformerManager
    php_orchestra_api.transformer.node.class: PHPOrchestra\ApiBundle\Transformer\NodeTransformer
    php_orchestra_api.transformer.template.class: PHPOrchestra\ApiBundle\Transformer\TemplateTransformer
    php_orchestra_api.transformer.area.class: PHPOrchestra\ApiBundle\Transformer\AreaTransformer
    php_orchestra_api.transformer.block.class: PHPOrchestra\ApiBundle\Transformer\BlockTransformer
    php_orchestra_api.transformer.ui_model.class: PHPOrchestra\ApiBundle\Transformer\UiModelTransformer
    php_orchestra_api.transformer.content_type.class: PHPOrchestra\ApiBundle\Transformer\ContentTypeTransformer
    php_orchestra_api.transformer.content_type_collection.class: PHPOrchestra\ApiBundle\Transformer\ContentTypeCollectionTransformer
    php_orchestra_api.transformer.content.class: PHPOrchestra\ApiBundle\Transformer\ContentTransformer
    php_orchestra_api.transformer.content_attribute.class: PHPOrchestra\ApiBundle\Transformer\ContentAttributeTransformer
    php_orchestra_api.transformer.content_collection.class: PHPOrchestra\ApiBundle\Transformer\ContentCollectionTransformer
    php_orchestra_api.transformer.site.class: PHPOrchestra\ApiBundle\Transformer\SiteTransformer
    php_orchestra_api.transformer.site_collection.class: PHPOrchestra\ApiBundle\Transformer\SiteCollectionTransformer
    php_orchestra_api.transformer.field_type.class: PHPOrchestra\ApiBundle\Transformer\FieldTypeTransformer

services:
    php_orchestra_api.transformer_manager:
        class: %php_orchestra_api.transformer_manager.class%
        arguments: [@router]
    php_orchestra_api.transformer.node:
        class: %php_orchestra_api.transformer.node.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.template:
        class: %php_orchestra_api.transformer.template.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.area:
        class: %php_orchestra_api.transformer.area.class%
        arguments: [@php_orchestra_model.repository.node]
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.block:
        class: %php_orchestra_api.transformer.block.class%
        arguments: [@php_orchestra_display.display_block_manager]
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.ui_model:
        class: %php_orchestra_api.transformer.ui_model.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_type:
        class: %php_orchestra_api.transformer.content_type.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_type_collection:
        class: %php_orchestra_api.transformer.content_type_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content:
        class: %php_orchestra_api.transformer.content.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_attribute:
        class: %php_orchestra_api.transformer.content_attribute.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_collection:
        class: %php_orchestra_api.transformer.content_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.site:
        class: %php_orchestra_api.transformer.site.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.site_collection:
        class: %php_orchestra_api.transformer.site_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.field_type:
        class: %php_orchestra_api.transformer.field_type.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy }
