parameters:
    open_orchestra_api.transformer.node.class: OpenOrchestra\ApiBundle\Transformer\NodeTransformer
    open_orchestra_api.transformer.node_collection.class: OpenOrchestra\ApiBundle\Transformer\NodeCollectionTransformer
    open_orchestra_api.transformer.template.class: OpenOrchestra\ApiBundle\Transformer\TemplateTransformer
    open_orchestra_api.transformer.area.class: OpenOrchestra\ApiBundle\Transformer\AreaTransformer
    open_orchestra_api.transformer.block.class: OpenOrchestra\ApiBundle\Transformer\BlockTransformer
    open_orchestra_api.transformer.block_collection.class: OpenOrchestra\ApiBundle\Transformer\BlockCollectionTransformer
    open_orchestra_api.transformer.ui_model.class: OpenOrchestra\ApiBundle\Transformer\UiModelTransformer
    open_orchestra_api.transformer.content_type.class: OpenOrchestra\ApiBundle\Transformer\ContentTypeTransformer
    open_orchestra_api.transformer.content_type_collection.class: OpenOrchestra\ApiBundle\Transformer\ContentTypeCollectionTransformer
    open_orchestra_api.transformer.content.class: OpenOrchestra\ApiBundle\Transformer\ContentTransformer
    open_orchestra_api.transformer.content_attribute.class: OpenOrchestra\ApiBundle\Transformer\ContentAttributeTransformer
    open_orchestra_api.transformer.content_collection.class: OpenOrchestra\ApiBundle\Transformer\ContentCollectionTransformer
    open_orchestra_api.transformer.status_collection.class: OpenOrchestra\ApiBundle\Transformer\StatusCollectionTransformer
    open_orchestra_api.transformer.site.class: OpenOrchestra\ApiBundle\Transformer\SiteTransformer
    open_orchestra_api.transformer.site_collection.class: OpenOrchestra\ApiBundle\Transformer\SiteCollectionTransformer
    open_orchestra_api.transformer.theme.class: OpenOrchestra\ApiBundle\Transformer\ThemeTransformer
    open_orchestra_api.transformer.theme_collection.class: OpenOrchestra\ApiBundle\Transformer\ThemeCollectionTransformer
    open_orchestra_api.transformer.role.class: OpenOrchestra\ApiBundle\Transformer\RoleTransformer
    open_orchestra_api.transformer.role_collection.class: OpenOrchestra\ApiBundle\Transformer\RoleCollectionTransformer
    open_orchestra_api.transformer.group.class: OpenOrchestra\ApiBundle\Transformer\GroupTransformer
    open_orchestra_api.transformer.group_collection.class: OpenOrchestra\ApiBundle\Transformer\GroupCollectionTransformer
    open_orchestra_api.transformer.redirection.class: OpenOrchestra\ApiBundle\Transformer\RedirectionTransformer
    open_orchestra_api.transformer.redirection_collection.class: OpenOrchestra\ApiBundle\Transformer\RedirectionCollectionTransformer
    open_orchestra_api.transformer.field_type.class: OpenOrchestra\ApiBundle\Transformer\FieldTypeTransformer
    open_orchestra_api.transformer.status.class: OpenOrchestra\ApiBundle\Transformer\StatusTransformer
    open_orchestra_api.transformer.keyword.class: OpenOrchestra\ApiBundle\Transformer\KeywordTransformer
    open_orchestra_api.transformer.keyword_collection.class: OpenOrchestra\ApiBundle\Transformer\KeywordCollectionTransformer
    open_orchestra_api.transformer.deleted.class: OpenOrchestra\ApiBundle\Transformer\DeletedTransformer
    open_orchestra_api.transformer.deleted_collection.class: OpenOrchestra\ApiBundle\Transformer\DeletedCollectionTransformer
    open_orchestra_api.transformer.link.class: OpenOrchestra\ApiBundle\Transformer\LinkTransformer
    open_orchestra_api.transformer.api_client.class: OpenOrchestra\ApiBundle\Transformer\ApiClientTransformer
    open_orchestra_api.transformer.api_client_collection.class: OpenOrchestra\ApiBundle\Transformer\ApiClientCollectionTransformer

services:
    open_orchestra_api.transformer.node:
        class: %open_orchestra_api.transformer.node.class%
        arguments:
            - @open_orchestra_base.manager.encryption
            - @open_orchestra_model.repository.site
            - @open_orchestra_model.repository.status
            - @event_dispatcher
            - @security.context
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.node_collection:
        class: %open_orchestra_api.transformer.node_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.template:
        class: %open_orchestra_api.transformer.template.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.area:
        class: %open_orchestra_api.transformer.area.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_backoffice.manager.area
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.block:
        class: %open_orchestra_api.transformer.block.class%
        arguments: 
            - @open_orchestra_backoffice.display_block_manager
            - @open_orchestra_backoffice.display_icon_manager
            - %open_orchestra_model.document.block.class%
            - @open_orchestra_backoffice.block_parameter_manager
            - @open_orchestra_backoffice.generate_form_manager
            - @open_orchestra_model.repository.node
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.block_collection:
        class: %open_orchestra_api.transformer.block_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.ui_model:
        class: %open_orchestra_api.transformer.ui_model.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.content_type:
        class: %open_orchestra_api.transformer.content_type.class%
        arguments:
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.content_type_collection:
        class: %open_orchestra_api.transformer.content_type_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.content:
        class: %open_orchestra_api.transformer.content.class%
        arguments:
            - @open_orchestra_model.repository.status
            - @event_dispatcher
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.content_attribute:
        class: %open_orchestra_api.transformer.content_attribute.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.content_collection:
        class: %open_orchestra_api.transformer.content_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.site:
        class: %open_orchestra_api.transformer.site.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.site_collection:
        class: %open_orchestra_api.transformer.site_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.theme:
        class: %open_orchestra_api.transformer.theme.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.theme_collection:
        class: %open_orchestra_api.transformer.theme_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.role:
        class: %open_orchestra_api.transformer.role.class%
        arguments:
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.role_collection:
        class: %open_orchestra_api.transformer.role_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.group:
        class: %open_orchestra_api.transformer.group.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.group_collection:
        class: %open_orchestra_api.transformer.group_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.redirection:
        class: %open_orchestra_api.transformer.redirection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.redirection_collection:
        class: %open_orchestra_api.transformer.redirection_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.status_collection:
        class: %open_orchestra_api.transformer.status_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.field_type:
        class: %open_orchestra_api.transformer.field_type.class%
        arguments:
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: open_orchestra_api.transformer.strategy }
    open_orchestra_api.transformer.status:
        class: %open_orchestra_api.transformer.status.class%
        arguments:
            - @security.context
            - @open_orchestra_model.repository.role
            - @open_orchestra_backoffice.manager.translation_choice
            - @translator
        tags:
            - { name: open_orchestra_api.transformer.strategy }
    open_orchestra_api.transformer.keyword:
        class: %open_orchestra_api.transformer.keyword.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.keyword_collection:
        class: %open_orchestra_api.transformer.keyword_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.deleted:
        class: %open_orchestra_api.transformer.deleted.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.deleted_collection:
        class: %open_orchestra_api.transformer.deleted_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.link:
        class: %open_orchestra_api.transformer.link.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.api_client:
        class: %open_orchestra_api.transformer.api_client.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_api.transformer.api_client_collection:
        class: %open_orchestra_api.transformer.api_client_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
