parameters:
    php_orchestra_api.transformer_manager.class: PHPOrchestra\ApiBundle\Transformer\TransformerManager
    php_orchestra_api.transformer.node.class: PHPOrchestra\ApiBundle\Transformer\NodeTransformer
    php_orchestra_api.transformer.node_collection.class: PHPOrchestra\ApiBundle\Transformer\NodeCollectionTransformer
    php_orchestra_api.transformer.template.class: PHPOrchestra\ApiBundle\Transformer\TemplateTransformer
    php_orchestra_api.transformer.area.class: PHPOrchestra\ApiBundle\Transformer\AreaTransformer
    php_orchestra_api.transformer.block.class: PHPOrchestra\ApiBundle\Transformer\BlockTransformer
    php_orchestra_api.transformer.ui_model.class: PHPOrchestra\ApiBundle\Transformer\UiModelTransformer
    php_orchestra_api.transformer.content_type.class: PHPOrchestra\ApiBundle\Transformer\ContentTypeTransformer
    php_orchestra_api.transformer.content_type_collection.class: PHPOrchestra\ApiBundle\Transformer\ContentTypeCollectionTransformer
    php_orchestra_api.transformer.content.class: PHPOrchestra\ApiBundle\Transformer\ContentTransformer
    php_orchestra_api.transformer.content_attribute.class: PHPOrchestra\ApiBundle\Transformer\ContentAttributeTransformer
    php_orchestra_api.transformer.content_collection.class: PHPOrchestra\ApiBundle\Transformer\ContentCollectionTransformer
    php_orchestra_api.transformer.status_collection.class: PHPOrchestra\ApiBundle\Transformer\StatusCollectionTransformer
    php_orchestra_api.transformer.site.class: PHPOrchestra\ApiBundle\Transformer\SiteTransformer
    php_orchestra_api.transformer.site_collection.class: PHPOrchestra\ApiBundle\Transformer\SiteCollectionTransformer
    php_orchestra_api.transformer.media.class: PHPOrchestra\ApiBundle\Transformer\MediaTransformer
    php_orchestra_api.transformer.media_collection.class: PHPOrchestra\ApiBundle\Transformer\MediaCollectionTransformer
    php_orchestra_api.transformer.theme.class: PHPOrchestra\ApiBundle\Transformer\ThemeTransformer
    php_orchestra_api.transformer.theme_collection.class: PHPOrchestra\ApiBundle\Transformer\ThemeCollectionTransformer
    php_orchestra_api.transformer.role.class: PHPOrchestra\ApiBundle\Transformer\RoleTransformer
    php_orchestra_api.transformer.role_collection.class: PHPOrchestra\ApiBundle\Transformer\RoleCollectionTransformer
    php_orchestra_api.transformer.field_type.class: PHPOrchestra\ApiBundle\Transformer\FieldTypeTransformer
    php_orchestra_api.transformer.status.class: PHPOrchestra\ApiBundle\Transformer\StatusTransformer
    php_orchestra_api.transformer.user.class: PHPOrchestra\ApiBundle\Transformer\UserTransformer
    php_orchestra_api.transformer.user_collection.class: PHPOrchestra\ApiBundle\Transformer\UserCollectionTransformer
    php_orchestra_api.transformer.keyword.class: PHPOrchestra\ApiBundle\Transformer\KeywordTransformer
    php_orchestra_api.transformer.keyword_collection.class: PHPOrchestra\ApiBundle\Transformer\KeywordCollectionTransformer
    php_orchestra_api.transformer.deleted.class: PHPOrchestra\ApiBundle\Transformer\DeletedTransformer
    php_orchestra_api.transformer.deleted_collection.class: PHPOrchestra\ApiBundle\Transformer\DeletedCollectionTransformer

services:
    php_orchestra_api.transformer_manager:
        class: %php_orchestra_api.transformer_manager.class%
        arguments: [@router]
    php_orchestra_api.transformer.node:
        class: %php_orchestra_api.transformer.node.class%
        arguments:
            - @php_orchestra_base.manager.encryption
            - @php_orchestra_model.repository.site
            - @php_orchestra_model.repository.status
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.node_collection:
        class: %php_orchestra_api.transformer.node_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.template:
        class: %php_orchestra_api.transformer.template.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.area:
        class: %php_orchestra_api.transformer.area.class%
        arguments: [@php_orchestra_model.repository.node, @php_orchestra_backoffice.manager.area]
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.block:
        class: %php_orchestra_api.transformer.block.class%
        arguments: 
            - @php_orchestra_display.display_block_manager
            - @php_orchestra_backoffice.display_icon_manager
            - %php_orchestra_model.document.block.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.ui_model:
        class: %php_orchestra_api.transformer.ui_model.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_type:
        class: %php_orchestra_api.transformer.content_type.class%
        arguments:
            - @php_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_type_collection:
        class: %php_orchestra_api.transformer.content_type_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content:
        class: %php_orchestra_api.transformer.content.class%
        arguments:
            - @php_orchestra_model.repository.status
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_attribute:
        class: %php_orchestra_api.transformer.content_attribute.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.content_collection:
        class: %php_orchestra_api.transformer.content_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.site:
        class: %php_orchestra_api.transformer.site.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.site_collection:
        class: %php_orchestra_api.transformer.site_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.media:
        class: %php_orchestra_api.transformer.media.class%
        arguments:
            - %php_orchestra_media.mediatheque.url%
            - %php_orchestra_media.thumbnail.configuration%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.media_collection:
        class: %php_orchestra_api.transformer.media_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.theme:
        class: %php_orchestra_api.transformer.theme.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.theme_collection:
        class: %php_orchestra_api.transformer.theme_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.role:
        class: %php_orchestra_api.transformer.role.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.role_collection:
        class: %php_orchestra_api.transformer.role_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.status_collection:
        class: %php_orchestra_api.transformer.status_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.field_type:
        class: %php_orchestra_api.transformer.field_type.class%
        arguments:
            - @php_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: php_orchestra_api.transformer.strategy }
    php_orchestra_api.transformer.status:
        class: %php_orchestra_api.transformer.status.class%
        arguments:
            - @security.context
            - @php_orchestra_model.repository.role
            - @php_orchestra_backoffice.manager.translation_choice
            - @translator
        tags:
            - { name: php_orchestra_api.transformer.strategy }
    php_orchestra_api.transformer.user:
        class: %php_orchestra_api.transformer.user.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.user_collection:
        class: %php_orchestra_api.transformer.user_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.keyword:
        class: %php_orchestra_api.transformer.keyword.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.keyword_collection:
        class: %php_orchestra_api.transformer.keyword_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.deleted:
        class: %php_orchestra_api.transformer.deleted.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
    php_orchestra_api.transformer.deleted_collection:
        class: %php_orchestra_api.transformer.deleted_collection.class%
        tags:
            - { name: php_orchestra_api.transformer.strategy}
