parameters:
    open_orchestra_user.document.group.class: OpenOrchestra\GroupBundle\Document\Group
    open_orchestra_group.document.node_group_role.class: OpenOrchestra\GroupBundle\Document\NodeGroupRole
    open_orchestra_group.type.group_choice.class: OpenOrchestra\GroupBundle\Form\Type\GroupDocumentType
    open_orchestra_group.listener.add_node_group_role_for_node.class: OpenOrchestra\GroupBundle\EventListener\AddNodeGroupRoleForNodeListener
    open_orchestra_group.listener.add_node_group_role_for_group.class: OpenOrchestra\GroupBundle\EventListener\AddNodeGroupRoleForGroupListener

services:
    open_orchestra_group.type.group_choice:
        class: %open_orchestra_group.type.group_choice.class%
        arguments:
            - %open_orchestra_user.document.group.class%
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: form.type, alias: oo_group_choice }
    open_orchestra_group.listener.add_node_group_role_for_node:
        class: %open_orchestra_group.listener.add_node_group_role_for_node.class%
        arguments:
            - %open_orchestra_group.document.node_group_role.class%
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
    open_orchestra_group.listener.add_node_group_role_for_group:
        class: %open_orchestra_group.listener.add_node_group_role_for_group.class%
        arguments:
            - %open_orchestra_group.document.node_group_role.class%
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
