services:
    open_orchestra_user_admin.navigation_panel.user:
        class: %open_orchestra_backoffice.navigation_panel.administration.class%
        arguments:
            - user
            - ROLE_ACCESS_USER
            - 395
        calls:
            - [ setTemplate, ['OpenOrchestraUserAdminBundle:AdministrationPanel:user.html.twig'] ]
        tags:
            - { name: open_orchestra_backoffice.navigation_panel.strategy }
